/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
  'index',
  'download',
  'integration',
  {
      type: 'category',
      label: 'Ad',
      collapsible: true,
      collapsed: false,
      items: [
          'hc-integration/iv',
          'hc-integration/rv',
          'hc-integration/bv',
          'hc-integration/nv',
          'hc-integration/sp',
      ]
  },
  'events',
  'remoteConfig',
  'IAP',
  'login',
   'other',
  {
      type: 'category',
      label: 'Build',
      items: [
        'sdk-projectsettings/sdk-projectsettings-ios',
        'sdk-projectsettings/sdk-projectsettings-android'
      ]
    }
  ]
};

module.exports = sidebars;
